# Generated by Django 4.0.5 on 2022-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodId',
            field=models.AutoField(db_column='foodId', primary_key=True, serialize=False),
        ),
    ]
