# Generated by Django 4.0.5 on 2022-06-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_alter_food_foodid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tableId', models.AutoField(db_column='tableId', primary_key=True, serialize=False)),
                ('isOccupied', models.BooleanField()),
                ('sessionId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(db_column='orderId', primary_key=True, serialize=False)),
                ('sessionId', models.IntegerField()),
                ('foodQuantity', models.IntegerField()),
                ('foodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.food')),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodApp.table')),
            ],
        ),
    ]
