# Generated by Django 4.0.5 on 2022-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_table_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='sessionId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
